In [1]:
import pandas as pd 
df = pd.read_csv("data/educ_figdp_1_Data.csv")
print(df)

     TIME                            GEO  \
0    2000  European Union (28 countries)
1    2001  European Union (28 countries)
2    2002  European Union (28 countries)
3    2003  European Union (28 countries)
4    2004  European Union (28 countries)
5    2005  European Union (28 countries)
6    2006  European Union (28 countries)
7    2007  European Union (28 countries)
8    2008  European Union (28 countries)
9    2009  European Union (28 countries)
10   2010  European Union (28 countries)
11   2011  European Union (28 countries)
12   2000  European Union (27 countries)
13   2001  European Union (27 countries)
14   2002  European Union (27 countries)
15   2003  European Union (27 countries)
16   2004  European Union (27 countries)
17   2005  European Union (27 countries)
18   2006  European Union (27 countries)
19   2007  European Union (27 countries)
20   2008  European Union (27 countries)
21   2009  European Union (27 countries)
22   2010  European Union (27 countries)
23   2011  European Union (27 countries)
24   2000  European Union (25 countries)
25   2001  European Union (25 countries)
26   2002  European Union (25 countries)
27   2003  European Union (25 countries)
28   2004  European Union (25 countries)
29   2005  European Union (25 countries)
..    ...                            ...
354  2006                       Slovenia
355  2007                       Slovenia
356  2008                       Slovenia
357  2009                       Slovenia
358  2010                       Slovenia
359  2011                       Slovenia
360  2000                       Slovakia
361  2001                       Slovakia
362  2002                       Slovakia
363  2003                       Slovakia
364  2004                       Slovakia
365  2005                       Slovakia
366  2006                       Slovakia
367  2007                       Slovakia
368  2008                       Slovakia
369  2009                       Slovakia
370  2010                       Slovakia
371  2011                       Slovakia
372  2000                        Finland
373  2001                        Finland
374  2002                        Finland
375  2003                        Finland
376  2004                        Finland
377  2005                        Finland
378  2006                        Finland
379  2007                        Finland
380  2008                        Finland
381  2009                        Finland
382  2010                        Finland
383  2011                        Finland

                                              INDIC_ED Value  \
0    Total public expenditure on education as % of ...     :
1    Total public expenditure on education as % of ...     :
2    Total public expenditure on education as % of ...  5.00
3    Total public expenditure on education as % of ...  5.03
4    Total public expenditure on education as % of ...  4.95
5    Total public expenditure on education as % of ...  4.92
6    Total public expenditure on education as % of ...  4.91
7    Total public expenditure on education as % of ...  4.92
8    Total public expenditure on education as % of ...  5.04
9    Total public expenditure on education as % of ...  5.38
10   Total public expenditure on education as % of ...  5.41
11   Total public expenditure on education as % of ...  5.25
12   Total public expenditure on education as % of ...  4.91
13   Total public expenditure on education as % of ...  4.99
14   Total public expenditure on education as % of ...  5.00
15   Total public expenditure on education as % of ...  5.04
16   Total public expenditure on education as % of ...  4.95
17   Total public expenditure on education as % of ...  4.92
18   Total public expenditure on education as % of ...  4.91
19   Total public expenditure on education as % of ...  4.93
20   Total public expenditure on education as % of ...  5.04
21   Total public expenditure on education as % of ...  5.38
22   Total public expenditure on education as % of ...  5.41
23   Total public expenditure on education as % of ...  5.25
24   Total public expenditure on education as % of ...  4.94
25   Total public expenditure on education as % of ...  5.02
26   Total public expenditure on education as % of ...  5.03
27   Total public expenditure on education as % of ...  5.06
28   Total public expenditure on education as % of ...  4.98
29   Total public expenditure on education as % of ...  4.95
..                                                 ...   ...
354  Total public expenditure on education as % of ...  5.72
355  Total public expenditure on education as % of ...  5.15
356  Total public expenditure on education as % of ...  5.20
357  Total public expenditure on education as % of ...  5.69
358  Total public expenditure on education as % of ...  5.68
359  Total public expenditure on education as % of ...  5.68
360  Total public expenditure on education as % of ...  3.92
361  Total public expenditure on education as % of ...  3.99
362  Total public expenditure on education as % of ...  4.31
363  Total public expenditure on education as % of ...  4.30
364  Total public expenditure on education as % of ...  4.19
365  Total public expenditure on education as % of ...  3.85
366  Total public expenditure on education as % of ...  3.80
367  Total public expenditure on education as % of ...  3.62
368  Total public expenditure on education as % of ...  3.61
369  Total public expenditure on education as % of ...  4.09
370  Total public expenditure on education as % of ...  4.22
371  Total public expenditure on education as % of ...  4.06
372  Total public expenditure on education as % of ...  5.89
373  Total public expenditure on education as % of ...  6.06
374  Total public expenditure on education as % of ...  6.22
375  Total public expenditure on education as % of ...  6.43
376  Total public expenditure on education as % of ...  6.42
377  Total public expenditure on education as % of ...  6.30
378  Total public expenditure on education as % of ...  6.18
379  Total public expenditure on education as % of ...  5.90
380  Total public expenditure on education as % of ...  6.10
381  Total public expenditure on education as % of ...  6.81
382  Total public expenditure on education as % of ...  6.85
383  Total public expenditure on education as % of ...  6.76

    Flag and Footnotes
0                  NaN
1                  NaN
2                    e
3                    e
4                    e
5                    e
6                    e
7                    e
8                    e
9                    e
10                   e
11                   e
12                   s
13                   s
14                   e
15                   e
16                   e
17                   e
18                   e
19                   e
20                   e
21                   e
22                   e
23                   e
24                   s
25                   s
26                   e
27                   e
28                   e
29                   e
..                 ...
354                NaN
355                NaN
356                NaN
357                NaN
358                NaN
359                NaN
360                  i
361                  d
362                  d
363                  d
364                  d
365                  d
366                  d
367                  d
368                  d
369                  d
370                  d
371                  d
372                NaN
373                NaN
374                NaN
375                NaN
376                NaN
377                NaN
378                NaN
379                NaN
380                NaN
381                NaN
382                NaN
383                NaN

[384 rows x 5 columns]

The most robust and consistent way of slicing ranges along arbitrary axes is described in the Selection by Position section detailing the .iloc method. For now, we explain the semantics of slicing using the [] operator.

With Series, the syntax works exactly as with an ndarray, returning a slice of the values and the corresponding labels:

In [3]:
print(df[:6])

   TIME                            GEO  \
0  2000  European Union (28 countries)
1  2001  European Union (28 countries)
2  2002  European Union (28 countries)
3  2003  European Union (28 countries)
4  2004  European Union (28 countries)
5  2005  European Union (28 countries)

                                            INDIC_ED Value Flag and Footnotes
0  Total public expenditure on education as % of ...     :                NaN
1  Total public expenditure on education as % of ...     :                NaN
2  Total public expenditure on education as % of ...  5.00                  e
3  Total public expenditure on education as % of ...  5.03                  e
4  Total public expenditure on education as % of ...  4.95                  e
5  Total public expenditure on education as % of ...  4.92                  e

In [4]:
print(df[::4])

     TIME                            GEO  \
0    2000  European Union (28 countries)
4    2004  European Union (28 countries)
8    2008  European Union (28 countries)
12   2000  European Union (27 countries)
16   2004  European Union (27 countries)
20   2008  European Union (27 countries)
24   2000  European Union (25 countries)
28   2004  European Union (25 countries)
32   2008  European Union (25 countries)
36   2000       Euro area (18 countries)
40   2004       Euro area (18 countries)
44   2008       Euro area (18 countries)
48   2000       Euro area (17 countries)
52   2004       Euro area (17 countries)
56   2008       Euro area (17 countries)
60   2000       Euro area (15 countries)
64   2004       Euro area (15 countries)
68   2008       Euro area (15 countries)
72   2000       Euro area (13 countries)
76   2004       Euro area (13 countries)
80   2008       Euro area (13 countries)
84   2000                        Belgium
88   2004                        Belgium
92   2008                        Belgium
96   2000                       Bulgaria
100  2004                       Bulgaria
104  2008                       Bulgaria
108  2000                 Czech Republic
112  2004                 Czech Republic
116  2008                 Czech Republic
..    ...                            ...
264  2000                        Hungary
268  2004                        Hungary
272  2008                        Hungary
276  2000                          Malta
280  2004                          Malta
284  2008                          Malta
288  2000                    Netherlands
292  2004                    Netherlands
296  2008                    Netherlands
300  2000                        Austria
304  2004                        Austria
308  2008                        Austria
312  2000                         Poland
316  2004                         Poland
320  2008                         Poland
324  2000                       Portugal
328  2004                       Portugal
332  2008                       Portugal
336  2000                        Romania
340  2004                        Romania
344  2008                        Romania
348  2000                       Slovenia
352  2004                       Slovenia
356  2008                       Slovenia
360  2000                       Slovakia
364  2004                       Slovakia
368  2008                       Slovakia
372  2000                        Finland
376  2004                        Finland
380  2008                        Finland

                                              INDIC_ED Value  \
0    Total public expenditure on education as % of ...     :
4    Total public expenditure on education as % of ...  4.95
8    Total public expenditure on education as % of ...  5.04
12   Total public expenditure on education as % of ...  4.91
16   Total public expenditure on education as % of ...  4.95
20   Total public expenditure on education as % of ...  5.04
24   Total public expenditure on education as % of ...  4.94
28   Total public expenditure on education as % of ...  4.98
32   Total public expenditure on education as % of ...  5.06
36   Total public expenditure on education as % of ...     :
40   Total public expenditure on education as % of ...  4.80
44   Total public expenditure on education as % of ...  4.94
48   Total public expenditure on education as % of ...     :
52   Total public expenditure on education as % of ...  4.80
56   Total public expenditure on education as % of ...  4.94
60   Total public expenditure on education as % of ...     :
64   Total public expenditure on education as % of ...  4.96
68   Total public expenditure on education as % of ...  4.95
72   Total public expenditure on education as % of ...     :
76   Total public expenditure on education as % of ...  4.95
80   Total public expenditure on education as % of ...  4.94
84   Total public expenditure on education as % of ...     :
88   Total public expenditure on education as % of ...  5.95
92   Total public expenditure on education as % of ...  6.43
96   Total public expenditure on education as % of ...  3.88
100  Total public expenditure on education as % of ...  4.40
104  Total public expenditure on education as % of ...  4.44
108  Total public expenditure on education as % of ...  3.83
112  Total public expenditure on education as % of ...  4.20
116  Total public expenditure on education as % of ...  3.92
..                                                 ...   ...
264  Total public expenditure on education as % of ...  4.50
268  Total public expenditure on education as % of ...  5.44
272  Total public expenditure on education as % of ...  5.10
276  Total public expenditure on education as % of ...  4.52
280  Total public expenditure on education as % of ...  4.66
284  Total public expenditure on education as % of ...  5.72
288  Total public expenditure on education as % of ...  4.98
292  Total public expenditure on education as % of ...  5.50
296  Total public expenditure on education as % of ...  5.50
300  Total public expenditure on education as % of ...  5.66
304  Total public expenditure on education as % of ...  5.48
308  Total public expenditure on education as % of ...  5.47
312  Total public expenditure on education as % of ...  4.87
316  Total public expenditure on education as % of ...  5.41
320  Total public expenditure on education as % of ...  5.08
324  Total public expenditure on education as % of ...  5.42
328  Total public expenditure on education as % of ...  5.10
332  Total public expenditure on education as % of ...  4.89
336  Total public expenditure on education as % of ...  2.88
340  Total public expenditure on education as % of ...  3.28
344  Total public expenditure on education as % of ...     :
348  Total public expenditure on education as % of ...     :
352  Total public expenditure on education as % of ...  5.74
356  Total public expenditure on education as % of ...  5.20
360  Total public expenditure on education as % of ...  3.92
364  Total public expenditure on education as % of ...  4.19
368  Total public expenditure on education as % of ...  3.61
372  Total public expenditure on education as % of ...  5.89
376  Total public expenditure on education as % of ...  6.42
380  Total public expenditure on education as % of ...  6.10

    Flag and Footnotes
0                  NaN
4                    e
8                    e
12                   s
16                   e
20                   e
24                   s
28                   e
32                   e
36                 NaN
40                   e
44                   e
48                 NaN
52                   e
56                   e
60                   u
64                   e
68                   e
72                   u
76                   e
80                   e
84                   u
88                   d
92                   d
96                 NaN
100                NaN
104                NaN
108                NaN
112                NaN
116                NaN
..                 ...
264                NaN
268                NaN
272                NaN
276                NaN
280                NaN
284                  i
288                NaN
292                NaN
296                NaN
300                NaN
304                NaN
308                NaN
312                  i
316                  d
320                  d
324                  d
328                  d
332                  d
336                NaN
340                NaN
344                  u
348                NaN
352                NaN
356                NaN
360                  i
364                  d
368                  d
372                NaN
376                NaN
380                NaN

[96 rows x 5 columns]

In [5]:
print(df[::-1])

     TIME                            GEO  \
383  2011                        Finland
382  2010                        Finland
381  2009                        Finland
380  2008                        Finland
379  2007                        Finland
378  2006                        Finland
377  2005                        Finland
376  2004                        Finland
375  2003                        Finland
374  2002                        Finland
373  2001                        Finland
372  2000                        Finland
371  2011                       Slovakia
370  2010                       Slovakia
369  2009                       Slovakia
368  2008                       Slovakia
367  2007                       Slovakia
366  2006                       Slovakia
365  2005                       Slovakia
364  2004                       Slovakia
363  2003                       Slovakia
362  2002                       Slovakia
361  2001                       Slovakia
360  2000                       Slovakia
359  2011                       Slovenia
358  2010                       Slovenia
357  2009                       Slovenia
356  2008                       Slovenia
355  2007                       Slovenia
354  2006                       Slovenia
..    ...                            ...
29   2005  European Union (25 countries)
28   2004  European Union (25 countries)
27   2003  European Union (25 countries)
26   2002  European Union (25 countries)
25   2001  European Union (25 countries)
24   2000  European Union (25 countries)
23   2011  European Union (27 countries)
22   2010  European Union (27 countries)
21   2009  European Union (27 countries)
20   2008  European Union (27 countries)
19   2007  European Union (27 countries)
18   2006  European Union (27 countries)
17   2005  European Union (27 countries)
16   2004  European Union (27 countries)
15   2003  European Union (27 countries)
14   2002  European Union (27 countries)
13   2001  European Union (27 countries)
12   2000  European Union (27 countries)
11   2011  European Union (28 countries)
10   2010  European Union (28 countries)
9    2009  European Union (28 countries)
8    2008  European Union (28 countries)
7    2007  European Union (28 countries)
6    2006  European Union (28 countries)
5    2005  European Union (28 countries)
4    2004  European Union (28 countries)
3    2003  European Union (28 countries)
2    2002  European Union (28 countries)
1    2001  European Union (28 countries)
0    2000  European Union (28 countries)

                                              INDIC_ED Value  \
383  Total public expenditure on education as % of ...  6.76
382  Total public expenditure on education as % of ...  6.85
381  Total public expenditure on education as % of ...  6.81
380  Total public expenditure on education as % of ...  6.10
379  Total public expenditure on education as % of ...  5.90
378  Total public expenditure on education as % of ...  6.18
377  Total public expenditure on education as % of ...  6.30
376  Total public expenditure on education as % of ...  6.42
375  Total public expenditure on education as % of ...  6.43
374  Total public expenditure on education as % of ...  6.22
373  Total public expenditure on education as % of ...  6.06
372  Total public expenditure on education as % of ...  5.89
371  Total public expenditure on education as % of ...  4.06
370  Total public expenditure on education as % of ...  4.22
369  Total public expenditure on education as % of ...  4.09
368  Total public expenditure on education as % of ...  3.61
367  Total public expenditure on education as % of ...  3.62
366  Total public expenditure on education as % of ...  3.80
365  Total public expenditure on education as % of ...  3.85
364  Total public expenditure on education as % of ...  4.19
363  Total public expenditure on education as % of ...  4.30
362  Total public expenditure on education as % of ...  4.31
361  Total public expenditure on education as % of ...  3.99
360  Total public expenditure on education as % of ...  3.92
359  Total public expenditure on education as % of ...  5.68
358  Total public expenditure on education as % of ...  5.68
357  Total public expenditure on education as % of ...  5.69
356  Total public expenditure on education as % of ...  5.20
355  Total public expenditure on education as % of ...  5.15
354  Total public expenditure on education as % of ...  5.72
..                                                 ...   ...
29   Total public expenditure on education as % of ...  4.95
28   Total public expenditure on education as % of ...  4.98
27   Total public expenditure on education as % of ...  5.06
26   Total public expenditure on education as % of ...  5.03
25   Total public expenditure on education as % of ...  5.02
24   Total public expenditure on education as % of ...  4.94
23   Total public expenditure on education as % of ...  5.25
22   Total public expenditure on education as % of ...  5.41
21   Total public expenditure on education as % of ...  5.38
20   Total public expenditure on education as % of ...  5.04
19   Total public expenditure on education as % of ...  4.93
18   Total public expenditure on education as % of ...  4.91
17   Total public expenditure on education as % of ...  4.92
16   Total public expenditure on education as % of ...  4.95
15   Total public expenditure on education as % of ...  5.04
14   Total public expenditure on education as % of ...  5.00
13   Total public expenditure on education as % of ...  4.99
12   Total public expenditure on education as % of ...  4.91
11   Total public expenditure on education as % of ...  5.25
10   Total public expenditure on education as % of ...  5.41
9    Total public expenditure on education as % of ...  5.38
8    Total public expenditure on education as % of ...  5.04
7    Total public expenditure on education as % of ...  4.92
6    Total public expenditure on education as % of ...  4.91
5    Total public expenditure on education as % of ...  4.92
4    Total public expenditure on education as % of ...  4.95
3    Total public expenditure on education as % of ...  5.03
2    Total public expenditure on education as % of ...  5.00
1    Total public expenditure on education as % of ...     :
0    Total public expenditure on education as % of ...     :

    Flag and Footnotes
383                NaN
382                NaN
381                NaN
380                NaN
379                NaN
378                NaN
377                NaN
376                NaN
375                NaN
374                NaN
373                NaN
372                NaN
371                  d
370                  d
369                  d
368                  d
367                  d
366                  d
365                  d
364                  d
363                  d
362                  d
361                  d
360                  i
359                NaN
358                NaN
357                NaN
356                NaN
355                NaN
354                NaN
..                 ...
29                   e
28                   e
27                   e
26                   e
25                   s
24                   s
23                   e
22                   e
21                   e
20                   e
19                   e
18                   e
17                   e
16                   e
15                   e
14                   e
13                   s
12                   s
11                   e
10                   e
9                    e
8                    e
7                    e
6                    e
5                    e
4                    e
3                    e
2                    e
1                  NaN
0                  NaN

[384 rows x 5 columns]

In [6]:
df[:5] = 0
print(df)

     TIME                            GEO  \
0       0                              0
1       0                              0
2       0                              0
3       0                              0
4       0                              0
5    2005  European Union (28 countries)
6    2006  European Union (28 countries)
7    2007  European Union (28 countries)
8    2008  European Union (28 countries)
9    2009  European Union (28 countries)
10   2010  European Union (28 countries)
11   2011  European Union (28 countries)
12   2000  European Union (27 countries)
13   2001  European Union (27 countries)
14   2002  European Union (27 countries)
15   2003  European Union (27 countries)
16   2004  European Union (27 countries)
17   2005  European Union (27 countries)
18   2006  European Union (27 countries)
19   2007  European Union (27 countries)
20   2008  European Union (27 countries)
21   2009  European Union (27 countries)
22   2010  European Union (27 countries)
23   2011  European Union (27 countries)
24   2000  European Union (25 countries)
25   2001  European Union (25 countries)
26   2002  European Union (25 countries)
27   2003  European Union (25 countries)
28   2004  European Union (25 countries)
29   2005  European Union (25 countries)
..    ...                            ...
354  2006                       Slovenia
355  2007                       Slovenia
356  2008                       Slovenia
357  2009                       Slovenia
358  2010                       Slovenia
359  2011                       Slovenia
360  2000                       Slovakia
361  2001                       Slovakia
362  2002                       Slovakia
363  2003                       Slovakia
364  2004                       Slovakia
365  2005                       Slovakia
366  2006                       Slovakia
367  2007                       Slovakia
368  2008                       Slovakia
369  2009                       Slovakia
370  2010                       Slovakia
371  2011                       Slovakia
372  2000                        Finland
373  2001                        Finland
374  2002                        Finland
375  2003                        Finland
376  2004                        Finland
377  2005                        Finland
378  2006                        Finland
379  2007                        Finland
380  2008                        Finland
381  2009                        Finland
382  2010                        Finland
383  2011                        Finland

                                              INDIC_ED Value  \
0                                                    0     0
1                                                    0     0
2                                                    0     0
3                                                    0     0
4                                                    0     0
5    Total public expenditure on education as % of ...  4.92
6    Total public expenditure on education as % of ...  4.91
7    Total public expenditure on education as % of ...  4.92
8    Total public expenditure on education as % of ...  5.04
9    Total public expenditure on education as % of ...  5.38
10   Total public expenditure on education as % of ...  5.41
11   Total public expenditure on education as % of ...  5.25
12   Total public expenditure on education as % of ...  4.91
13   Total public expenditure on education as % of ...  4.99
14   Total public expenditure on education as % of ...  5.00
15   Total public expenditure on education as % of ...  5.04
16   Total public expenditure on education as % of ...  4.95
17   Total public expenditure on education as % of ...  4.92
18   Total public expenditure on education as % of ...  4.91
19   Total public expenditure on education as % of ...  4.93
20   Total public expenditure on education as % of ...  5.04
21   Total public expenditure on education as % of ...  5.38
22   Total public expenditure on education as % of ...  5.41
23   Total public expenditure on education as % of ...  5.25
24   Total public expenditure on education as % of ...  4.94
25   Total public expenditure on education as % of ...  5.02
26   Total public expenditure on education as % of ...  5.03
27   Total public expenditure on education as % of ...  5.06
28   Total public expenditure on education as % of ...  4.98
29   Total public expenditure on education as % of ...  4.95
..                                                 ...   ...
354  Total public expenditure on education as % of ...  5.72
355  Total public expenditure on education as % of ...  5.15
356  Total public expenditure on education as % of ...  5.20
357  Total public expenditure on education as % of ...  5.69
358  Total public expenditure on education as % of ...  5.68
359  Total public expenditure on education as % of ...  5.68
360  Total public expenditure on education as % of ...  3.92
361  Total public expenditure on education as % of ...  3.99
362  Total public expenditure on education as % of ...  4.31
363  Total public expenditure on education as % of ...  4.30
364  Total public expenditure on education as % of ...  4.19
365  Total public expenditure on education as % of ...  3.85
366  Total public expenditure on education as % of ...  3.80
367  Total public expenditure on education as % of ...  3.62
368  Total public expenditure on education as % of ...  3.61
369  Total public expenditure on education as % of ...  4.09
370  Total public expenditure on education as % of ...  4.22
371  Total public expenditure on education as % of ...  4.06
372  Total public expenditure on education as % of ...  5.89
373  Total public expenditure on education as % of ...  6.06
374  Total public expenditure on education as % of ...  6.22
375  Total public expenditure on education as % of ...  6.43
376  Total public expenditure on education as % of ...  6.42
377  Total public expenditure on education as % of ...  6.30
378  Total public expenditure on education as % of ...  6.18
379  Total public expenditure on education as % of ...  5.90
380  Total public expenditure on education as % of ...  6.10
381  Total public expenditure on education as % of ...  6.81
382  Total public expenditure on education as % of ...  6.85
383  Total public expenditure on education as % of ...  6.76

    Flag and Footnotes
0                    0
1                    0
2                    0
3                    0
4                    0
5                    e
6                    e
7                    e
8                    e
9                    e
10                   e
11                   e
12                   s
13                   s
14                   e
15                   e
16                   e
17                   e
18                   e
19                   e
20                   e
21                   e
22                   e
23                   e
24                   s
25                   s
26                   e
27                   e
28                   e
29                   e
..                 ...
354                NaN
355                NaN
356                NaN
357                NaN
358                NaN
359                NaN
360                  i
361                  d
362                  d
363                  d
364                  d
365                  d
366                  d
367                  d
368                  d
369                  d
370                  d
371                  d
372                NaN
373                NaN
374                NaN
375                NaN
376                NaN
377                NaN
378                NaN
379                NaN
380                NaN
381                NaN
382                NaN
383                NaN

[384 rows x 5 columns]